CREATE TABLE CONFIG (
  GUILD_ID                  VARCHAR(20) NOT NULL,

  REPORT_THRESHHOLD         INT         NOT NULL,
  REPORT_EXPIRED_THRESHHOLD INT         NOT NULL,
  REPORT_GUILD_ID           VARCHAR(20),
  REPORT_CHANNEL_ID         VARCHAR(20),

  PRIMARY KEY (GUILD_ID)
);

CREATE TABLE USERS (
  GUILD_ID   VARCHAR(20) NOT NULL,
  USER_ID    VARCHAR(20) NOT NULL,
  DAY_TIME   DATETIME    NOT NULL,
  IS_LEAVING BOOLEAN,

  PRIMARY KEY (GUILD_ID, USER_ID, DAY_TIME)
);

CREATE TABLE CHANNELS (
  CHANNEL_ID   VARCHAR(20) NOT NULL,
  CHANNEL_NAME VARCHAR(50) NOT NULL,
  GUILD_ID     VARCHAR(20) NOT NULL,
  OWNER_ID     VARCHAR(20),

  PRIMARY KEY (CHANNEL_ID),
  FOREIGN KEY (GUILD_ID, OWNER_ID) REFERENCES USERS (GUILD_ID, USER_ID)
);

CREATE TABLE SERVER_ANALYTICS (
  DAY_DATE    DATE NOT NULL,
  USER_JOINED INT  NOT NULL,
  USER_LEFT   INT  NOT NULL,

  PRIMARY KEY (DAY_DATE)
);

CREATE TABLE CHANNEL_ANALYTICS (
  CHANNEL_ID    VARCHAR(20) NOT NULL,
  DAY_DATE      DATE        NOT NULL,
  MESSAGE_COUNT INT         NOT NULL,

  PRIMARY KEY (CHANNEL_ID, DAY_DATE),
  FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS (CHANNEL_ID)
);

CREATE TABLE USER_REPORTS (
  ID          INT AUTO_INCREMENT NOT NULL,
  USER_ID     VARCHAR(20)        NOT NULL,
  DESCRIPTION VARCHAR(2000)      NOT NULL,
  DAY_TIME    DATETIME           NOT NULL,
  POINTS      INT                NOT NULL,

  REPORTER    VARCHAR(20)        NOT NULL,
  EXPIRED     BOOL               NOT NULL DEFAULT FALSE,
  DELETED     BOOL               NOT NULL DEFAULT FALSE,

  PRIMARY KEY (ID, USER_ID, DAY_TIME)
);